\newcommand{\mse@bla}{
  \pagestyle{empty}

  \begin{center}
     \parbox[c][0.98\textheight][t]{1.0\textwidth}{
        \begin{center}

           \mse@str@proposedby\\[2ex]
           \mse@proposedby
           \vspace{2.5cm} 

           \begin{minipage}[t]{0.49\textwidth}
              \begin{flushleft}
                 {\bf \mse@str@advisor}\\
                 \mse@advisor\\
              \end{flushleft}
           \end{minipage}
           \hfill
           \begin{minipage}[t]{0.49\textwidth}
              \begin{flushright}
                 {\bf \mse@str@headofmse}\\
                 \mse@headofmse\\
              \end{flushright}
           \end{minipage}

        \end{center}
     }
  \end{center}
  \cleardoublepage
}
